services:
  # PHP-FPM mit Development Server Port
  php:
    image: php:8.3-fpm
    container_name: jg_php
    ports:
      - "8000:8000"  # Laravel Development Server
    volumes:
      - ./backend/api:/var/www/html
    networks:
      - jeder_gewinnt
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: jeder_gewinnt
      DB_USERNAME: jg_user
      DB_PASSWORD: jg_password
      REDIS_HOST: redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: jg_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/api:/var/www/html
      - ./infrastructure/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jeder_gewinnt
    depends_on:
      - php

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: jg_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jeder_gewinnt
      MYSQL_USER: jg_user
      MYSQL_PASSWORD: jg_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jeder_gewinnt

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: jg_redis
    ports:
      - "6379:6379"
    networks:
      - jeder_gewinnt

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jg_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - jeder_gewinnt

networks:
  jeder_gewinnt:
    driver: bridge

volumes:
  mysql_data:

  scheduler:
  build: ./backend/api
  command: php artisan schedule:work
  volumes:
    - ./backend/api:/var/www/html
  depends_on:
    - mysql